# Generated by Django 3.1 on 2021-09-28 12:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kelas',
            },
        ),
        migrations.CreateModel(
            name='Libur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Hari Libur',
            },
        ),
        migrations.CreateModel(
            name='PresensiSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_tutup', models.TimeField(default=datetime.time(11, 0))),
                ('sabtu_libur', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Pengaturan Presensi',
            },
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('no_induk', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('no_induk_nasional', models.CharField(blank=True, max_length=30)),
                ('nama', models.CharField(max_length=50)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50)),
                ('tanggal_lahir', models.DateField(blank=True, max_length=10, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=2)),
                ('telepon', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('foto', models.ImageField(blank=True, max_length=50, upload_to='uploads/')),
                ('petugas_kelas', models.BooleanField(default=True)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidak.kelas')),
            ],
            options={
                'verbose_name_plural': 'Siswa',
            },
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('HADIR', 'HADIR'), ('SAKIT', 'SAKIT'), ('IZIN', 'IZIN'), ('ABSEN', 'ABSEN')], max_length=5)),
                ('tanggal', models.DateField(auto_now_add=True, max_length=8)),
                ('waktu', models.TimeField(auto_now=True)),
                ('no_induk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidak.siswa')),
            ],
            options={
                'verbose_name_plural': 'Presensi',
            },
        ),
    ]
