# Generated by Django 3.1 on 2021-09-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sidak', '0002_auto_20210928_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presensi',
            name='no_induk',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='presensi', to='sidak.siswa'),
        ),
    ]
