# Generated by Django 3.1 on 2021-09-28 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidak', '0003_auto_20210928_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensisetting',
            name='waktu_buka',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
