# Generated by Django 3.1 on 2021-09-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sidak', '0004_presensisetting_waktu_buka'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensisetting',
            name='kode_preview',
            field=models.CharField(default='preview123', max_length=20),
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='uploads/')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField()),
                ('petugas', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='surat', to='sidak.siswa')),
                ('subjek', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='subjek_surat', to='sidak.siswa')),
            ],
            options={
                'verbose_name_plural': 'Surat',
            },
        ),
    ]
