# Generated by Django 3.1 on 2021-09-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidak', '0005_auto_20210930_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='foto',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
